repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        exclude: ^notebooks/
      # Run the formatter.
      - id: ruff-format
        exclude: ^notebooks/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]
        files: ^src/
        exclude: ^(tests/|notebooks/)

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: uv run pytest --maxfail=1 -q
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
